<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class MenuBuilderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin_menus = [
            [
                'id' => 1,
                'name' => 'main_menu',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'footer_menu_one',
                'created_at' => '2023-09-13 05:31:22',
                'updated_at' => '2023-09-13 05:31:22',
            ],
            [
                'id' => 3,
                'name' => 'footer_menu_two',
                'created_at' => '2023-09-13 05:34:53',
                'updated_at' => '2023-09-13 05:34:53',
            ],
            [
                'id' => 4,
                'name' => 'footer_menu_three',
                'created_at' => '2023-09-13 05:35:29',
                'updated_at' => '2023-09-13 05:35:29',
            ],
        ];

        $admin_menu_items = [
            [
                'id' => 2,
                'label' => 'Home',
                'link' => '/',
                'parent_id' => 0,
                'sort' => 2,
                'class' => null,
                'menu_id' => 2,
                'depth' => 0,
                'created_at' => '2023-09-13 06:00:59',
                'updated_at' => '2023-09-13 06:14:43',
            ],
            [
                'id' => 3,
                'label' => 'About',
                'link' => '/about',
                'parent_id' => 0,
                'sort' => 1,
                'class' => null,
                'menu_id' => 2,
                'depth' => 0,
                'created_at' => '2023-09-13 06:02:18',
                'updated_at' => '2023-09-13 06:16:10',
            ],
            [
                'id' => 4,
                'label' => 'Contact',
                'link' => '/contact',
                'parent_id' => 0,
                'sort' => 0,
                'class' => null,
                'menu_id' => 2,
                'depth' => 0,
                'created_at' => '2023-09-13 06:03:39',
                'updated_at' => '2023-09-13 06:16:10',
            ],
            [
                'id' => 5,
                'label' => 'Our Service',
                'link' => '#',
                'parent_id' => 0,
                'sort' => 3,
                'class' => null,
                'menu_id' => 2,
                'depth' => 0,
                'created_at' => '2023-09-13 06:04:12',
                'updated_at' => '2023-09-13 06:04:12',
            ],
            [
                'id' => 6,
                'label' => 'More About Us',
                'link' => '#',
                'parent_id' => 0,
                'sort' => 4,
                'class' => null,
                'menu_id' => 2,
                'depth' => 0,
                'created_at' => '2023-09-13 06:04:27',
                'updated_at' => '2023-09-13 06:04:27',
            ],
            [
                'id' => 7,
                'label' => 'Trams and Condition',
                'link' => '/trams-and-conditions',
                'parent_id' => 0,
                'sort' => 3,
                'class' => null,
                'menu_id' => 3,
                'depth' => 0,
                'created_at' => '2023-09-13 06:56:59',
                'updated_at' => '2023-09-13 07:00:59',
            ],
            [
                'id' => 8,
                'label' => 'Privacy Policy',
                'link' => '/privacy-policy',
                'parent_id' => 0,
                'sort' => 2,
                'class' => null,
                'menu_id' => 3,
                'depth' => 0,
                'created_at' => '2023-09-13 06:57:29',
                'updated_at' => '2023-09-13 07:00:59',
            ],
            [
                'id' => 9,
                'label' => 'More',
                'link' => '#',
                'parent_id' => 0,
                'sort' => 4,
                'class' => null,
                'menu_id' => 3,
                'depth' => 0,
                'created_at' => '2023-09-13 06:59:45',
                'updated_at' => '2023-09-13 07:00:59',
            ],
            [
                'id' => 10,
                'label' => 'Blogs',
                'link' => '/blogs',
                'parent_id' => 0,
                'sort' => 0,
                'class' => null,
                'menu_id' => 3,
                'depth' => 0,
                'created_at' => '2023-09-13 07:00:20',
                'updated_at' => '2023-09-13 07:00:56',
            ],
            [
                'id' => 11,
                'label' => 'Chefs',
                'link' => '/chefs',
                'parent_id' => 0,
                'sort' => 1,
                'class' => null,
                'menu_id' => 3,
                'depth' => 0,
                'created_at' => '2023-09-13 07:00:41',
                'updated_at' => '2023-09-13 07:01:05',
            ],
            [
                'id' => 12,
                'label' => 'Contact',
                'link' => '/contact',
                'parent_id' => 0,
                'sort' => 0,
                'class' => null,
                'menu_id' => 4,
                'depth' => 0,
                'created_at' => '2023-09-13 07:03:56',
                'updated_at' => '2023-09-13 07:04:12',
            ],
            [
                'id' => 13,
                'label' => 'About',
                'link' => '/about',
                'parent_id' => 0,
                'sort' => 1,
                'class' => null,
                'menu_id' => 4,
                'depth' => 0,
                'created_at' => '2023-09-13 07:04:11',
                'updated_at' => '2023-09-13 07:04:33',
            ],
            [
                'id' => 14,
                'label' => 'Blogs',
                'link' => '/bogs',
                'parent_id' => 0,
                'sort' => 3,
                'class' => null,
                'menu_id' => 4,
                'depth' => 0,
                'created_at' => '2023-09-13 07:04:33',
                'updated_at' => '2023-09-13 07:04:33',
            ],
            [
                'id' => 15,
                'label' => 'Home',
                'link' => '/',
                'parent_id' => 0,
                'sort' => 0,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2023-09-13 07:21:58',
                'updated_at' => '2023-09-13 07:22:21',
            ],
            [
                'id' => 16,
                'label' => 'About',
                'link' => '/about',
                'parent_id' => 0,
                'sort' => 1,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2023-09-13 07:22:20',
                'updated_at' => '2023-09-13 07:22:50',
            ],
            [
                'id' => 17,
                'label' => 'Chefs',
                'link' => '/chef',
                'parent_id' => 23,
                'sort' => 5,
                'class' => null,
                'menu_id' => 1,
                'depth' => 1,
                'created_at' => '2023-09-13 07:22:49',
                'updated_at' => '2023-09-13 07:40:11',
            ],
            [
                'id' => 18,
                'label' => 'Blogs',
                'link' => '/blogs',
                'parent_id' => 0,
                'sort' => 2,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2023-09-13 07:23:05',
                'updated_at' => '2023-09-13 09:09:04',
            ],
            [
                'id' => 19,
                'label' => 'Contact',
                'link' => '/contact',
                'parent_id' => 0,
                'sort' => 3,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2023-09-13 07:23:23',
                'updated_at' => '2023-09-13 07:27:29',
            ],
            [
                'id' => 20,
                'label' => 'Testimonials',
                'link' => '/testimonials',
                'parent_id' => 23,
                'sort' => 6,
                'class' => null,
                'menu_id' => 1,
                'depth' => 1,
                'created_at' => '2023-09-13 07:24:10',
                'updated_at' => '2023-09-13 07:27:35',
            ],
            [
                'id' => 21,
                'label' => 'Privacy Policy',
                'link' => '/privacy-policy',
                'parent_id' => 23,
                'sort' => 7,
                'class' => null,
                'menu_id' => 1,
                'depth' => 1,
                'created_at' => '2023-09-13 07:24:53',
                'updated_at' => '2023-09-13 07:27:17',
            ],
            [
                'id' => 22,
                'label' => 'Trams and Conditions',
                'link' => '/trams-and-conditions',
                'parent_id' => 23,
                'sort' => 8,
                'class' => null,
                'menu_id' => 1,
                'depth' => 1,
                'created_at' => '2023-09-13 07:25:15',
                'updated_at' => '2023-09-13 07:27:29',
            ],
            [
                'id' => 23,
                'label' => 'Pages',
                'link' => '#',
                'parent_id' => 0,
                'sort' => 4,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2023-09-13 07:26:58',
                'updated_at' => '2023-09-13 07:27:32',
            ],
            [
                'id' => 24,
                'label' => 'Products',
                'link' => '/products',
                'parent_id' => 0,
                'sort' => 1,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2023-09-13 07:26:58',
                'updated_at' => '2023-09-13 07:27:32',
            ],
        ];

        DB::table('admin_menus')->insert($admin_menus);

        DB::table('admin_menu_items')->insert($admin_menu_items);

    }
}
